image: quay.io/buildah/stable:v1.11.0

variables:
  IMAGE: 'quay.io/bigkevmcd/java-demo:master-' + vars.CI_COMMIT_SHORT_SHA

build-image:
  rules:
    - if: vars.CI_COMMIT_BRANCH != 'master'
      when: never
  script:
    - buildah bud --format=oci --layers -f ./Dockerfile -t $IMAGE .
    - buildah push $IMAGE docker://$IMAGE
