image: maven:3-openjdk-11

build-jar:
  rules:
    - if: vars.CI_COMMIT_BRANCH != 'master'
      when: never
  script:
    - mvn clean package
  artifacts:
    paths:
      - ./build/target/ci-demo-0.0.1-SNAPSHOT.jar
